# Generated by Django 5.1.2 on 2024-10-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_products_remove_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
