# Generated by Django 5.1.2 on 2024-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtype',
            field=models.CharField(max_length=20, null=True, verbose_name='Category Subtype'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Sale', 'Sale'), ('Product', 'Product')], max_length=20, null=True, verbose_name='Category Type'),
        ),
    ]
