# Generated by Django 5.1.2 on 2024-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/img/default.jpg', null=True, upload_to='static/assets/img/product_img/'),
        ),
    ]
