# Generated by Django 5.1.2 on 2024-10-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/img/default.jpg', null=True, upload_to='product_images/'),
        ),
    ]
