# Generated by Django 5.1.2 on 2024-11-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
